# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatTheNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatTheNews
  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'SnackBar.swift'
  pod 'McPicker', '~> 3.0.0'
end
